package ingenieria.economica;

import javax.swing.JOptionPane;
import java.text.DecimalFormat;

public class CALCULO extends javax.swing.JFrame {

    int opc = 0;
    double inversion=0, años=0, tasa=0,gradiente;
    double F=0,P=0,A=0,G=0;
    DecimalFormat df=new DecimalFormat("0.0000");
    public CALCULO() {
        setTitle("INGENIERA ECONOMICA");
        initComponents();
        setSize(900, 490);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        binversion = new javax.swing.JTextField();
        baños = new javax.swing.JTextField();
        btasa = new javax.swing.JTextField();
        fac = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        res = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        facc = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bgra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jButton5.setText("P/F");

        jButton7.setText("P/F");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("FACTOR ACTUALMENTE SELECCIONADO");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(binversion);
        binversion.setBounds(190, 150, 136, 36);
        getContentPane().add(baños);
        baños.setBounds(190, 190, 136, 35);
        getContentPane().add(btasa);
        btasa.setBounds(190, 230, 136, 37);

        fac.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(fac);
        fac.setBounds(510, 110, 340, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("AÑOS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 190, 170, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("INVERSION INICIAL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 150, 170, 41);

        jButton2.setText("P/F");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(624, 159, 105, 35);

        jButton3.setText("P/A");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(735, 159, 105, 35);

        jButton4.setText("F/P");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(513, 159, 105, 35);

        jButton6.setText("A/P");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(513, 206, 105, 37);

        jButton9.setText("A/F");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(735, 206, 105, 37);

        jButton10.setText("F/A");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(624, 206, 105, 37);

        jButton11.setText("G A");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(513, 249, 105, 37);

        jButton12.setText("G G");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(624, 249, 105, 37);

        jButton13.setText("CALCULAR");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(735, 249, 105, 37);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("FACTORES DE INTERES COMPUESTO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 10, 820, 60);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("TASA");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 230, 170, 36);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("INGRESE LOS SIGUIENTES DATOS");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 100, 310, 36);

        res.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        res.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        res.setText("RESULTADO = ");
        getContentPane().add(res);
        res.setBounds(290, 370, 340, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("FACTOR ACTUALMENTE SELECCIONADO");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(510, 70, 340, 50);

        facc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        facc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        facc.setText("FACTOR:");
        getContentPane().add(facc);
        facc.setBounds(260, 320, 340, 50);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("GRADIENTE");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 270, 170, 36);

        bgra.setEnabled(false);
        bgra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgraActionPerformed(evt);
            }
        });
        getContentPane().add(bgra);
        bgra.setBounds(190, 270, 136, 37);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fon.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 900, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try{
        if (binversion.getText().equals("") || baños.getText().equals("") || btasa.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No debe de haber ningun campo vacío!");
        } else if (opc == 0) {
            JOptionPane.showMessageDialog(null, "Debe de seleccionar una opcion para proseguir!");
        } else {
            inversion = Double.parseDouble(binversion.getText());
            años = Double.parseDouble(baños.getText());
            tasa = Double.parseDouble(btasa.getText());
            tasa=tasa/100;
            if (opc == 1) {
                F=inversion*Math.pow((1+tasa), años);
                facc.setText("FACTOR: F/P");
                res.setText("RESULTADO = "+df.format(F));
                F=0;
            }else if(opc==2){
                P=inversion*(1/(Math.pow(1+tasa,años)));
                facc.setText("FACTOR: P/F");
                res.setText("RESULTADO = "+df.format(P));
                P=0;
            }else if(opc==3){
                P=inversion*((Math.pow(1+tasa,años)-1)/(tasa*(Math.pow(1+tasa, años))));
                facc.setText("FACTOR: P/A");
                res.setText("RESULTADO = "+df.format(P));
                P=0;
            }else if(opc==4){
                A=inversion*((tasa*(Math.pow(1+tasa,años)))/((Math.pow(1+tasa,años))-1));
                facc.setText("FACTOR: A/P");
                res.setText("RESULTADO = "+df.format(A));
                A=0;
            }else if(opc==5){
                F=inversion*(((Math.pow(1+tasa,años))-1)/tasa);
                facc.setText("FACTOR: F/A");
                res.setText("RESULTADO = "+df.format(F));
                F=0;
            }else if(opc==6){
                A=inversion*((tasa)/((Math.pow(1+tasa,años))-1));
                facc.setText("FACTOR: A/F");
                res.setText("RESULTADO = "+df.format(A));
                A=0;
            }else if(opc==7){
                facc.setText("FACTOR: GRADIENTE ARITMETICO");
                G=((años*inversion)/(1+tasa));
                res.setText("RESULTADO = "+df.format(G));
                G=0;
            }else if(opc==8){
                gradiente=Double.parseDouble(bgra.getText());
                facc.setText("FACTOR: GRADIENTE GEOMETRICO");
                G=inversion*((1-(Math.pow((1+gradiente)/(1+tasa),años)))/(tasa-gradiente));
                res.setText("RESULTADO = "+df.format(G));
                G=0;
            }
        }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Debe de ingresar numeros solamente");
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        opc = 1;
        fac.setText("F/P");
        bgra.setEnabled(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        opc = 2;
        fac.setText("P/F");
        bgra.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        opc = 3;
        fac.setText("P/A");
        bgra.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        opc = 4;
        fac.setText("A/P");
        bgra.setEnabled(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        opc = 5;
        fac.setText("F/A");
        bgra.setEnabled(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        opc = 6;
        fac.setText("A/F");
        bgra.setEnabled(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        opc = 7;
        bgra.setEnabled(false);
        fac.setText("G A");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        opc = 8;
        fac.setText("G G");
        bgra.setEnabled(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void bgraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bgraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CALCULO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CALCULO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CALCULO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CALCULO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CALCULO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField baños;
    private javax.swing.JTextField bgra;
    private javax.swing.JTextField binversion;
    private javax.swing.JTextField btasa;
    private javax.swing.JLabel fac;
    private javax.swing.JLabel facc;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel res;
    // End of variables declaration//GEN-END:variables
}
